DOC: make manual notebook for lambda-K-Pi
ComPWA/gluex-nstar pull request #101
Opened 2024-08-27 16:29 UTC by shenvitor

2024-08-30 16:27 UTC, shenvitor commented
![Screenshot 2024-08-30 at 18 23 30](https://github.com/user-attachments/assets/16ba34c3-10b7-4532-9919-a0afaa11b5ec)
The Dalitz plot in this PR looks awesome rn 🍡  !
(hopefully it's correctly formulate, I will double-check later next week)

2024-09-02 07:54 UTC, redeboer requested changes
I don't see the use of creating an (almost) exact copy of the eta pi p notebook. That one is more for playing around with a super simple amplitude model that has three subsystems and one resonance in each, where you can then see the effect of angular momentum. As we know, that model is not physical.

For $\Lambda K \pi$, we have to step up the game. This is supposed to be a model that formulates the model from the (preferably) `ampform-dpd` notebook manually, so that it can then be tweaked with a proper treatment of e.g. #58.

What is currently missing are multiple resonances, treatment of spin of the final-state particles, spin alignment, etc. That also makes the UI design not suitable. I would therefore start to try to reproduce the model (symbolic only!) from `ampform-dpd.ipynb`.

2024-09-02 07:54 UTC, redeboer commented on docs/lambda-k-pi/index.md
> +manual-symbolic
Why call this `manual-symbolic`, not `manual`?

2024-09-02 08:45 UTC, shenvitor commented
> I don't see the use of creating an (almost) exact copy of the eta pi p notebook. That one is more for playing around with a super simple amplitude model that has three subsystems and one resonance in each, where you can then see the effect of angular momentum. As we know, that model is not physical.
> 
> For $\Lambda K \pi$, we have to step up the game. This is supposed to be a model that formulates the model from the (preferably) `ampform-dpd` notebook manually, so that it can then be tweaked with a proper treatment of e.g. #58.
> 
> What is currently missing are multiple resonances, treatment of spin of the final-state particles, spin alignment, etc. That also makes the UI design not suitable. I would therefore start to try to reproduce the model (symbolic only!) from `ampform-dpd.ipynb`.

I think the idea here is to have multiple notebook for symbolic manually in different levels of complications, from simplest to some more complicated ones later  in this reaction section.

2024-09-02 08:52 UTC, redeboer commented
> I think the idea here is to have multiple notebooks for symbolic manually in different levels of complications, from simplest to some more complicated ones later in this reaction section.

That's fine, but to have multiple copies of the same idea is just a maintenance burden. The 'manual' eta pi p notebook is just a pedagogical exercise: some **spinless** initial and final state ("p gamma to eta pi p" is even misleading) with **one** resonance per subsystem. In fact, the only difference between the notebooks now are the labels of those three imaginary resonances and the imaginary final state.

In the end, what we want to achieve is a **physical** description of $p\gamma \to \Lambda K \pi$, that is, with correct description of the production process, all dominating resonances in each subsystem, and a proper treatment of spin alignment of the final state. There is no generic package that can do that, so we need to go through a process of manually formulating each of these components to gain understanding of its behaviour.

2024-09-02 08:55 UTC, redeboer commented
I'm fine with adding this notebook, but a lot needs to be done to this PR first, for instance:
- rotations for each decay node (see model from `ampform.ipynb` and `ampform-dpd.ipynb`
- a sum over an arbitrary number of resonances

2024-09-02 08:58 UTC, shenvitor commented
Okay, I see your points. Yup we can make it more accurate than now.

2024-09-02 12:32 UTC, shenvitor commented
Rejected by @redeboer, so close this as not planned for now, but we can still see the record if we need it in the future.

2024-09-02 12:32 UTC, closed without merging