Symbolic expression to form amplitude models
ComPWA/gluex-nstar pull request #13
Opened 2024-05-24 16:56 UTC by shenvitor

2024-06-19 14:15 UTC, shenvitor commented
The idea now is to split this branch to one more branch because one for $\eta \pi p$ and the other is $\Lambda K^+ \pi^0$

2024-06-24 07:30 UTC, redeboer commented
So the PR has been split up into
- https://github.com/ComPWA/gluex-nstar/pull/13
- https://github.com/ComPWA/gluex-nstar/pull/28
- https://github.com/ComPWA/gluex-nstar/pull/29

Which ones is ready for review?

2024-06-24 07:33 UTC, redeboer requested changes
For the three PRs, could you use an imperative sentence for the PR title?
https://compwa.github.io/develop#commit-conventions
Doesn't have to be conventional (with a category), but just the standard following the standard commit guidelines
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project

2024-06-24 08:40 UTC, shenvitor commented
> For the three PRs, could you use an imperative sentence for the PR title?
> https://compwa.github.io/develop#commit-conventions
> Doesn't have to be conventional (with a category), but just the standard following the standard commit guidelines
> https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project
> 
> Optionally you can enforce that with this workflow
> https://github.com/ComPWA/tensorwaves/blob/94d8a62c60dc8de50b2dd4023d563c735d76add8/.github/workflows/pr-linting.yml
> but that also enforces the use of conventional commit categories.

Okay 🙌

2024-07-09 14:18 UTC, shenvitor commented
Dear @redeboer 
This PR is now ready for re-review and merge

2024-07-12 10:05 UTC, redeboer commented on .github/workflows/ci-docs.yml
> +    ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
@shenvitor I smuggled in this DX improvement: it aborts CI if additional commits are pushed, in order to save CI time 🌍

2024-07-12 10:15 UTC, redeboer approved these changes
Großartig 🙌

2024-07-12 10:15 UTC, merged