Change md table to directly obtained values from particle_db html table
ComPWA/gluex-nstar pull request #55
Opened 2024-07-12 23:44 UTC by shenvitor

see the diff.

2024-07-12 23:46 UTC, shenvitor commented
by the way I suggest disabling ruff: D103 Missing docstring in public function 

otherwise, I need to add words in even a small function... :(

2024-07-13 06:40 UTC, redeboer commented
> by the way I suggest disabling ruff: D103 Missing docstring in public function

Yes good point. But only for notebooks, i.e. through the `per-file-ignores` table. I think there already is an entry for `**.ipynb`.

2024-07-13 06:50 UTC, redeboer commented
I would try to make the table more concise, e.g. combine spin, parity, isospin etc into one row with a $J^{PC}(I^G)$ string. See also https://qrules--274.org.readthedocs.build/274/usage/visualize.html#other-state-renderings from https://github.com/ComPWA/qrules/pull/274.

2024-07-18 10:18 UTC, redeboer commented
> In the database, 
> 𝐽
>  is not directly shown, I think I need to find a way to find/calculate it?

No you can just use the existing attributes of each `Particle` instance. $J$ is `spin`, $I$ is `isospin.magnitude` etc. (Of course, you need to check whether these values are defined at all or `None`.)
It is uncommon to render $I_z$, but you can do so in another column.

2024-07-18 10:23 UTC, shenvitor commented
> > In the database, J is not directly shown, I think I need to find a way to find/calculate it?
> 
> No you can just use the existing attributes of each `Particle` instance. J is `spin`, I is `isospin.magnitude` etc. (Of course, you need to check whether these values are defined at all or `None`.) It is uncommon to render Iz, but you can do so in another column.

I see... originally I was thinking about $J=L+S$, and so $L=0$ here you mean?

2024-07-18 10:27 UTC, redeboer commented
Exactly, just have a look at what's happening in this PR (there the $J^{PC}(I^G)$ values are inserted into graphviz with unicode, but same idea for a latex table).

> I would try to make the table more concise, e.g. combine spin, parity, isospin etc into one row with a JPC(IG) string. See also https://qrules--274.org.readthedocs.build/274/usage/visualize.html#other-state-renderings from [ComPWA/qrules#274](https://github.com/ComPWA/qrules/pull/274).

2024-07-23 18:06 UTC, shenvitor commented
OK now it's ready for review :)

2024-07-24 07:54 UTC, shenvitor commented
Weird... Now all the math/equation/symbols are not loading in the RTD website preview 🤔

2024-07-24 09:07 UTC, redeboer commented
Yes it's an old issue with the Sphinx rendering, see e.g. https://github.com/jupyter-book/jupyter-book/issues/1501. That's why I usually resort to building a custom Markdown table string and rendering it with [`Markdown`](https://ipython.readthedocs.io/en/8.26.0/api/generated/IPython.display.html#IPython.display.Markdown). That also allows you to do more advanced renderings, but it is a bit more work.

2024-07-24 10:10 UTC, redeboer requested changes

2024-07-24 10:10 UTC, redeboer commented on docs/ampform/LambdaKpi0.ipynb
> +    "        jpc_ig = rf\"${spin_latex}^{{{format_parity(particle.parity)}{format_parity(particle.c_parity)}}}$\"\n",
I would put all this stuff in a function that does `Particle` -> `str` $J^PC(I^G)$

2024-07-24 10:10 UTC, redeboer commented on docs/ampform/LambdaKpi0.ipynb
> +    "    return str(parity)\n",
I would `raise NotImplementedError` to avoid feeding this function the wrong input

2024-07-24 10:29 UTC, shenvitor commented on docs/ampform/LambdaKpi0.ipynb
> +    "    return rf\"$\\frac{{{value.numerator}}}{{{value.denominator}}}$\"\n",
the difference is to add an extra $$ because somewhere I need it ⭕

2024-07-24 10:31 UTC, shenvitor commented on docs/ampform/LambdaKpi0.ipynb
> +    "display(HTML(mathjax_script + html_table))"
what's pretty repr?

2024-07-24 10:35 UTC, redeboer commented on docs/ampform/LambdaKpi0.ipynb
> +    "    return rf\"$\\frac{{{value.numerator}}}{{{value.denominator}}}$\"\n",
That can't be a solution 😅

2024-07-31 19:54 UTC, redeboer commented
@shenvitor For the rendering of `Markdown` table in Sphinx that you implemented in 4073d24: the problem is that you need to set [`nb_render_markdown_format = "myst"`](https://myst-nb.readthedocs.io/en/v1.1.1/configuration.html#rendering) in `conf.py` 🎉

2024-08-01 14:01 UTC, redeboer requested changes

2024-08-02 14:48 UTC, redeboer approved these changes
Awesome 🧇

2024-08-02 14:58 UTC, merged