Ipywidgets
ComPWA/gluex-nstar pull request #56
Opened 2024-07-13 00:41 UTC by shenvitor

2024-07-13 06:46 UTC, redeboer commented
Good to have a dedicated playground notebook!
Eventually I would remove it, but it is useful to try the mechanism with a small example. The examples you give will have to be modified though: the plot has to be updated rather than redrawn, so we need to define the figure outside the function and define some global state for the line that is to be ploted. See the examples on ComPWA.

2024-07-19 14:55 UTC, shenvitor commented
Collecting some reference tutorials:
https://kapernikov.com/ipywidgets-with-matplotlib/

2024-07-19 15:07 UTC, redeboer commented
Seems that the code in that tutorial is not the most efficient — it removes the plot and then creates a new one (still; better than removing the entire figure).

You may also consider using [`mpl-interactions`](https://mpl-interactions.readthedocs.io). This has good (and fast) support for matplotlib's core plotting objects, but you loose flexibility, e.g. you can't quickly draw an additional line that updates along with your parameters.

An example of an interactive histogram can be found here:
https://compwa.github.io/ampform-dpd/comparison/d2kkk.html
Note how the final cell defines a global state `lines`, which is a list of `step` lines that are generated `if lines is None` and that are updated with `set_ydata()` upon changes to the sliders (i.e. the parameter values). The code isn't pretty, but it is flexible enough to extend with additional indicators on the plot.

2024-08-01 12:44 UTC, redeboer requested changes

2024-08-05 17:12 UTC, redeboer commented on docs/ampform/LambdaKpi0.ipynb
> +    "    w.HBox([\n",
@shenvitor this is what I meant: the 'hugging' of `([` in the `HBox` constructor. That only works if preview for Ruff is activated for the formatter (not just the linter), see 66a312d.

2024-08-05 17:13 UTC, redeboer approved these changes
Awesome 🌵

2024-08-05 17:13 UTC, merged