FEAT: add sliders in sympy etapipi nb
ComPWA/gluex-nstar pull request #95
Opened 2024-08-23 18:11 UTC by shenvitor

- Closes #94

2024-08-23 19:06 UTC, redeboer requested changes

2024-08-23 19:06 UTC, redeboer commented on docs/eta-pi-p/manual.ipynb
> +     "hide-input"
Make the plot with the histograms interactive as well. Can be done in the same PR now that you know the trick ;)

2024-08-23 19:06 UTC, redeboer commented on docs/eta-pi-p/manual.ipynb
> +   },
This cell with slider definitions should be `hide-input` and `scroll-input`

2024-08-23 19:06 UTC, redeboer commented on docs/eta-pi-p/manual.ipynb
> +    "UI"
Don't display the `UI` here
```suggestion
    "UI = w.Tab(tab_contents, titles=resonances_name)"
```

2024-08-27 09:38 UTC, shenvitor commented on docs/eta-pi-p/manual.ipynb
> +    "s23, m_delta, gamma_delta = sp.symbols(r\"s_{23} m_{\\Delta^+} \\Gamma_{\\Delta^+}\")\n",
I don't agree..

2024-08-27 10:09 UTC, redeboer commented on docs/eta-pi-p/manual.ipynb
> +    "s23, m_delta, gamma_delta = sp.symbols(r\"s_{23} m_{\\Delta^+} \\Gamma_{\\Delta^+}\")\n",
See https://github.com/MagicStack/MagicPython/issues/114

2024-08-27 11:55 UTC, redeboer approved these changes
Cool 😎

2024-08-27 12:02 UTC, merged